### PR TITLE
Add Beth's GWAS Blood Pressure notebooks

### PR DESCRIPTION
**Pull request by aofarrel**
These are tested and appear fully functional in Terra, however, due to the nature of the second notebook some additional testing is still pending.

Pending:
* herzogification of 13.3 (second notebook)
* herzog-friendly form of section 13.6 (second notebook) 
* just generally checking part 13's output is as expected (second notebook)

### CODE REVIEW

**Comment by aofarrel** [comment]
_(xpost from last commit's comment)_
When I let the GRM run for about 12 hours, it seemed to got stuck. However it did output "2020-11-25 17:25:16 Hail: INFO: Wrote all 666 blocks of 2727214 x 1028 matrix with block size 4096." at some point, and it appears this GRM is used by the Genesis GWAS workflow which ran successfully on 1.4.1 (but not master). This means either it ran successfully and never exited the cell correctly, or it got stuck and the partial output was enough to run the workflow correctly (but we can't trust the results). More investigation is needed.

**Comment by bethsheets** [comment]
I'm ok merging this with master due to the immediate need and further exploring the GRM issue with a smaller dataset.

**Comment by aofarrel** [comment]
_(partial xpost from Slack)_
The gitlab pipeline failures on the second notebook seem inevitable.  The second notebook runs terra_data_table_util.ipynb in the same workspace. It then uses those functions to run functions in this notebook. This triggers F821 on flake8 since it considers it an undefined name. #noqa will prevent flake8 from firing but the next step in gitlab will throw an error for seemingly the same reason.

**Comment by DailyDreaming** [comment]
@aofarrel @bethsheets This error appears to be a 404 and not a linting error: https://biodata-integration-tests.net/databiosphere/bdcat_notebooks/-/jobs/11726

Should this be fixed before pushing to users?  I suspect that outside users will run into the same issue.

**Comment by aofarrel** [comment]
Timings for using just chr1 from Amish:
* mt.count() --> **Just over a minute**
* mt.write(bucket + 'MyProject_MAFgt0.01.mt', overwrite=True) --> **04:42**
* hl.export_vcf(mt, bucket + 'MyProject_MAFgt0.01.vcf.bgz', parallel='header_per_shard') --> **0:59**
* pruned_variant_table = hl.ld_prune(mt.GT, r2=0.2, bp_window_size=500000, block_size=1024) --> **38:49**
* grm = hl.genetic_relatedness_matrix(mt.GT).to_numpy() --> **0:46**
* Total elapsed time (including some on-the-spot debugging on my part so would be lower for users) --> **1:32:52**

**Comment by aofarrel** [comment]
Yoinking these into master where gitlab should be happier with pyspark

**Pull request merged**
