### PR TITLE
Make my life, in particular, a little bit easier

### PR DESCRIPTION
**Pull request by aofarrel**
I copied an existing script but with one letter capitalized and that seemed to fix it. I don't claim to understand xargs, but I can at least use `make` to some extent now.

Does not change the default behavior of `make` to avoid breaking things for everybody else, just adds an additional option for me.

### CODE REVIEW

**Review by xbrianh — CHANGES_REQUESTED** [review]
This is too much content to address problems with xargs.

Preferable solutions:
  1. Install a compliant version of xargs on your system
  2. Introduce an env var:
      ```
      find notebooks -mindepth 1 -maxdepth 1 -type d -print0 | sort -f -z | ${SPLIT_NULL}
      ```

**Comment by aofarrel** [comment]
This feels like an awkward solution, but it was more educational then trying to re-install something that doesn't have a homebrew tap. How's this?

**Comment by aofarrel** [comment]
This is functional, but it turns out that this issue can be fixed on Catalina with `brew install findutils` and paying attention to the caveats (ie, adding `/usr/local/opt/findutils/libexec/gnubin` to PATH).

**Comment by aofarrel** [comment]
_Forbidden knowledge ahead_
On the extremely unlikely chance some student with a non-adminstrator account on a rental laptop stumbles upon this and can't install the good version of xargs, this works with the built in Mac version of xargs, but is bad practice.

```
if [ ${USER} = user-of-cursed-xargs ]; then
  PRINT="-print"
  SORT="sort -f"
  XARGS="xargs"
else
  PRINT="-print0"
  SORT="sort -f -z"
  XARGS="xargs -r0"
fi
for nb in $(find notebooks -mindepth 1 -maxdepth 1 -type d ${PRINT} | ${SORT} | ${XARGS}); do
```

**Pull request closed without merging**
